name: streamx
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  adaptive_dialog: ^2.1.0
  appinio_video_player: ^1.2.2
  auto_size_text: ^3.0.0
  build_runner: ^2.4.7
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  easy_localization: ^3.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.9
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^13.0.1
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  logger: ^2.1.0
  lottie: ^3.1.0
  persistent_bottom_nav_bar_v2: ^5.0.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  video_player: ^2.8.2

dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants
  filename: assets.dart
  field_prefix: null
