name: streamx
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # dependency for support multi-language i.e arabic 
  flutter_localizations:
        sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.6
  #A build system for Dart code generation and modular compilation
  build_runner: ^2.4.7
  # State management
  flutter_bloc: ^8.1.3
  # Code generator (mainly used with cubit & retrofit)
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  # for dependency injection
  get_it: ^7.6.4
  # Automatically generate code for converting to and from JSON by annotating Dart classes
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1
  # Networking
  dio: ^5.3.3
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  pretty_dio_logger: ^1.3.1
  # localization
  intl: ^0.18.1
  easy_localization: ^3.0.3
  # for splash screen
  flutter_native_splash: ^2.3.5
  # An SVG rendering and widget library for Flutter, which allows painting
  flutter_svg: ^2.0.9
  # for adapting screen and font size.
  flutter_screenutil: ^5.9.0
  # for routing and navigation
  go_router: ^13.0.1
  auto_size_text: ^3.0.0
  video_player: ^2.8.2
  # for date and time
  shared_preferences: ^2.2.2
  # for show dialog based on platform (android, ios)
  adaptive_dialog: ^2.1.0
  # pie chart for showing data
  carousel_slider: ^4.2.1
  # great package for gif animations
  lottie: ^3.1.0
  # for handling the location of the user
  internet_connection_checker: ^1.0.0+1
  # help us to make a good looking for debugging and logging purpose 
  logger: ^2.1.0
  # it's a video player package that can play videos from the internet or the local storage
  appinio_video_player: ^1.2.2
  # shimmer effect for loading instead of the normal loading indicator
  shimmer: ^3.0.0
  persistent_bottom_nav_bar_v2: ^5.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
       
  

flutter_assets:
  assets_path: assets/
  output_path: lib/core/constants
  filename: assets.dart
  field_prefix: null